---
booktitle: Proceedings of the 30th International Conference on Algorithmic Learning
  Theory
shortname: ALT
year: '2019'
volume: 98
start: 2019-03-22
end: 2019-03-24
published: 2019-03-10
url: http://proceedings.mlr.press
author:
  name: PMLR
conference_number: '30'
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: ALT19
month: 0
cycles: false
bibtex_editor: Garivier, Aur\'elien and Kale, Satyen
editor:
- given: Aurélien
  family: Garivier
- given: Satyen
  family: Kale
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 30th International Conference on Algorithmic Learning Theory
    Held in Chicago, Illinois on 22-24 March 2019

  Published as Volume 98 by the Proceedings of Machine Learning Research on 10 March 2019.

  Volume Edited by:
    Aurélien Garivier
    Satyen Kale

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 22--24 Mar
baseurl: "/v98"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v98
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Algorithmic Learning Theory
  url: http://alt2019.algorithmiclearningtheory.org/
  location: Chicago, Illinois
  dates:
  - 2019-03-22
  - 2019-03-23
  - 2019-03-24
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
